### PR TITLE
Update to 1.20.6

### PR DESCRIPTION
**Pull request by CommandGenius**
yeah

### CODE REVIEW

**Comment by CommandGenius** [comment]
Download a compiled version [here](https://github.com/CommandGenius/on-soul-fire/releases/tag/1.20.6)

**Comment by MoriyaShiine** [comment]
I have 1.20.6 versions of my mods available [on my Ko-fi](https://ko-fi.com/moriyashiine)! They will be available publicly later.

**Comment by CommandGenius** [comment]
> I have 1.20.6 versions of my mods available [on my Ko-fi](https://ko-fi.com/moriyashiine)! They will be available publicly later.

my bad, i'll remove the compiled release i made.

**Comment by MoriyaShiine** [comment]
No worries!

**Pull request closed without merging**
